In [3]:
import numpy as np
import pandas as pd

data5000 = pd.read_csv('movie_metadata.csv')
data5000.head(20)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000

In [4]:
data5000.shape

(5043, 28)

### Let's remove unnecesary columns
---

In [26]:
data5000.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [28]:
needed_columns = [
    'movie_title',
    'title_year',
    'genres',
    'director_name',
    'actor_1_name',
    'actor_2_name',
    'actor_3_name',
    'imdb_score',
    'plot_keywords',
    'language',]
data5000 = data5000[needed_columns]
data5000.head(10)

,movie_title,title_year,genres,director_name,actor_1_name,actor_2_name,actor_3_name,imdb_score,plot_keywords,language
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,7.9,avatar|future|marine|native|paraplegic,English
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,7.1,goddess|marriage ceremony|marriage proposal|pi...,English
2,Spectre,2015.0,Action|Adventure|Thriller,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,6.8,bomb|espionage|sequel|spy|terrorist,English
3,The Dark Knight Rises,2012.0,Action|Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,8.5,deception|imprisonment|lawlessness|police offi...,English
4,Star Wars: Episode VII - The Force Awakens ...,NaN,Documentary,Doug Walker,Doug Walker,Rob Walker,NaN,7.1,NaN,NaN
5,John Carter,2012.0,Action|Adventure|Sci-Fi,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,6.6,alien|american civil war|male nipple|mars|prin...,English
6,Spider-Man 3,2007.0,Action|Adventure|Romance,Sam Raimi,J.K. Simmons,James Franco,Kirsten Dunst,6.2,sandman|spider man|symbiote|venom|villain,English
7,Tangled,2010.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Nathan Greno,Brad Garrett,Donna Murphy,M.C. Gainey,7.8,17th century|based on fairy tale|disney|flower...,English
8,Avengers: Age of Ultron,2015.0,Action|Adventure|Sci-Fi,Joss Whedon,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,7.5,artificial intelligence|based on comic book|ca...,English
9,Harry Potter and the Half-Blood Prince,2009.0,Adventure|Family|Fantasy|Mystery,David Yates,Alan Rickman,Daniel Radcliffe,Rupert Grint,7.5,blood|book|love|potion|professor,English

In [ ]:
import matplotlib.pyplot as plt

data5000['title_year'].value_counts(dropna=False).sort_index().plot(kind='barh', figsize=(15, 15))
plt.title('Number of Movies Released Each Year')
plt.show()

## We have movies from 1916 to 2016, the rest is not included in the dataset.
### Let's look at the nan values and the earliest movie (out of curiosity)
---

In [31]:
data5000.dropna(subset=['title_year']).sort_values('title_year', ascending=True).head(10)

,movie_title,title_year,genres,director_name,actor_1_name,actor_2_name,actor_3_name,imdb_score,plot_keywords,language
4810,Intolerance: Love's Struggle Throughout the Ages,1916.0,Drama|History|War,D.W. Griffith,Lillian Gish,Mae Marsh,Walter Long,8.0,huguenot|intolerance|medicis|protestant|wedding,NaN
4958,Over the Hill to the Poorhouse,1920.0,Crime|Drama,Harry F. Millarde,Stephen Carr,Johnnie Walker,Mary Carr,4.8,family relationships|gang|idler|poorhouse|thief,NaN
4885,The Big Parade,1925.0,Drama|Romance|War,King Vidor,John Gilbert,Renée Adorée,Claire Adams,8.3,chewing gum|climbing a tree|france|translation...,NaN
2734,Metropolis,1927.0,Drama|Sci-Fi,Fritz Lang,Brigitte Helm,Gustav Fröhlich,Rudolf Klein-Rogge,8.3,art deco|bible quote|dance|silent film|worker,German
4812,The Broadway Melody,1929.0,Musical|Romance,Harry Beaumont,Anita Page,Bessie Love,Charles King,6.3,sibling rivalry|singer|sister act|whistling|wi...,English
4664,Pandora's Box,1929.0,Crime|Drama|Romance,Georg Wilhelm Pabst,Louise Brooks,Francis Lederer,Fritz Kortner,8.0,escape|femme fatale|german expressionism|lust|...,German
3960,Hell's Angels,1930.0,Drama|War,Howard Hughes,Jean Harlow,Marian Marsh,James Hall,7.8,bomb|bombing mission|munitions|oxford|royal fl...,English
3755,A Farewell to Arms,1932.0,Drama|Romance|War,Frank Borzage,Gary Cooper,Helen Hayes,Adolphe Menjou,6.6,1910s|ambulance driver|italy|lake|nurse,English
4898,She Done Him Wrong,1933.0,Comedy|Drama|History|Musical|Romance,Lowell Sherman,Mae West,Gilbert Roland,Louise Beavers,6.5,captain|marriage proposal|saloon|saloon singer...,English
4786,42nd Street,1933.0,Comedy|Musical|Romance,Lloyd Bacon,Ginger Rogers,Dick Powell,George Brent,7.7,chorus girl|chorus line|director|gala premiere...,English

In [37]:
data5000.query('title_year.isnull()').head(10)

,movie_title,title_year,genres,director_name,actor_1_name,actor_2_name,actor_3_name,imdb_score,plot_keywords,language
4,Star Wars: Episode VII - The Force Awakens ...,NaN,Documentary,Doug Walker,Doug Walker,Rob Walker,NaN,7.1,NaN,NaN
177,Miami Vice,NaN,Action|Crime|Drama|Mystery|Thriller,NaN,Don Johnson,Philip Michael Thomas,John Diehl,7.5,cult tv|detective|drugs|police|undercover,English
260,The A-Team,NaN,Action|Adventure|Crime,NaN,George Peppard,Dirk Benedict,Dwight Schultz,7.6,1980s|cult tv|famous opening theme|good versus...,English
279,"10,000 B.C.",NaN,Comedy,Christopher Barnard,Mathew Buck,NaN,NaN,7.2,NaN,NaN
404,Hannibal,NaN,Crime|Drama|Horror|Mystery|Thriller,NaN,Caroline Dhavernas,Scott Thompson,Hettienne Park,8.6,blood|cannibalism|fbi|manipulation|psychiatrist,English
459,Daredevil,NaN,Action|Adventure|Crime|Drama|Sci-Fi|Thriller,NaN,Elden Henson,Royce Johnson,Charlie Cox,8.8,corruption|lawyer|partnership|superhero|vigilante,English
479,Bewitched,NaN,Comedy|Family|Fantasy,NaN,Elizabeth Montgomery,Agnes Moorehead,Dick York,7.6,connecticut|magic|marriage|witch|witchcraft,English
537,Constantine,NaN,Drama|Fantasy|Horror|Thriller,NaN,Harold Perrineau,Matt Ryan,Charles Halford,7.5,based on comic|based on comic book|dc arrowver...,English
543,Life,NaN,Crime|Drama|Mystery,NaN,Adam Arkin,Brent Sexton,Damian Lewis,8.3,cop|murder|partner|police|protective male,English
593,Sleepy Hollow,NaN,Adventure|Drama|Fantasy|Mystery|Thriller,NaN,Nicole Beharie,Katia Winter,Lyndie Greenwood,7.5,apocalypse|death|husband wife relationship|mot...,English

#### After checking a few null values, I understood that the movies with null values are actually series. So they have a beginning and end year, and they are not movies. That's why I will remove them.
--------

In [35]:
new_data5000 = data5000.dropna(subset=needed_columns)

##### Even after dropping the empty rows, we still have a lot of rows which is great.

In [36]:
new_data5000.shape

(4772, 10)

In [38]:
new_data5000.head(10)

,movie_title,title_year,genres,director_name,actor_1_name,actor_2_name,actor_3_name,imdb_score,plot_keywords,language
0,Avatar,2009.0,Action|Adventure|Fantasy|Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,7.9,avatar|future|marine|native|paraplegic,English
1,Pirates of the Caribbean: At World's End,2007.0,Action|Adventure|Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,7.1,goddess|marriage ceremony|marriage proposal|pi...,English
2,Spectre,2015.0,Action|Adventure|Thriller,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,6.8,bomb|espionage|sequel|spy|terrorist,English
3,The Dark Knight Rises,2012.0,Action|Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,8.5,deception|imprisonment|lawlessness|police offi...,English
5,John Carter,2012.0,Action|Adventure|Sci-Fi,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,6.6,alien|american civil war|male nipple|mars|prin...,English
6,Spider-Man 3,2007.0,Action|Adventure|Romance,Sam Raimi,J.K. Simmons,James Franco,Kirsten Dunst,6.2,sandman|spider man|symbiote|venom|villain,English
7,Tangled,2010.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Nathan Greno,Brad Garrett,Donna Murphy,M.C. Gainey,7.8,17th century|based on fairy tale|disney|flower...,English
8,Avengers: Age of Ultron,2015.0,Action|Adventure|Sci-Fi,Joss Whedon,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,7.5,artificial intelligence|based on comic book|ca...,English
9,Harry Potter and the Half-Blood Prince,2009.0,Adventure|Family|Fantasy|Mystery,David Yates,Alan Rickman,Daniel Radcliffe,Rupert Grint,7.5,blood|book|love|potion|professor,English
10,Batman v Superman: Dawn of Justice,2016.0,Action|Adventure|Sci-Fi,Zack Snyder,Henry Cavill,Lauren Cohan,Alan D. Purwin,6.9,based on comic book|batman|sequel to a reboot|...,English

##### I think movie year is not really relevant for our ML model. So I will train two different models with and without the year. Also, the language does not seem relevant. I don't want the model to be biased.

In [56]:
new_data5000.movie_title[0]

'Avatar\xa0'

In [ ]:
# I will remove the /xa0 from the movie titles.
new_data5000['movie_title'].str.replace('\xa0', '')

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
5                                    John Carter
                          ...
5035                                 El Mariachi
5036                             The Mongol King
5037                                   Newlyweds
5038                     Signed Sealed Delivered
5042                           My Date with Drew
Name: movie_title, Length: 4772, dtype: object

In [59]:
new_data5000.movie_title[0]

'Avatar '

In [60]:
new_data5000['genres'] = new_data5000['genres'].str.replace('|', ' ')
new_data5000['plot_keywords'] = new_data5000['plot_keywords'].str.replace('|', ' ')

C:\Users\ufaci\AppData\Local\Temp\ipykernel_6836\2115730443.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data5000['genres'] = new_data5000['genres'].str.replace('|', ' ')
C:\Users\ufaci\AppData\Local\Temp\ipykernel_6836\2115730443.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data5000['plot_keywords'] = new_data5000['plot_keywords'].str.replace('|', ' ')

In [61]:
new_data5000.head(10)

,movie_title,title_year,genres,director_name,actor_1_name,actor_2_name,actor_3_name,imdb_score,plot_keywords,language
0,Avatar,2009.0,Action Adventure Fantasy Sci-Fi,James Cameron,CCH Pounder,Joel David Moore,Wes Studi,7.9,avatar future marine native paraplegic,English
1,Pirates of the Caribbean: At World's End,2007.0,Action Adventure Fantasy,Gore Verbinski,Johnny Depp,Orlando Bloom,Jack Davenport,7.1,goddess marriage ceremony marriage proposal pi...,English
2,Spectre,2015.0,Action Adventure Thriller,Sam Mendes,Christoph Waltz,Rory Kinnear,Stephanie Sigman,6.8,bomb espionage sequel spy terrorist,English
3,The Dark Knight Rises,2012.0,Action Thriller,Christopher Nolan,Tom Hardy,Christian Bale,Joseph Gordon-Levitt,8.5,deception imprisonment lawlessness police offi...,English
5,John Carter,2012.0,Action Adventure Sci-Fi,Andrew Stanton,Daryl Sabara,Samantha Morton,Polly Walker,6.6,alien american civil war male nipple mars prin...,English
6,Spider-Man 3,2007.0,Action Adventure Romance,Sam Raimi,J.K. Simmons,James Franco,Kirsten Dunst,6.2,sandman spider man symbiote venom villain,English
7,Tangled,2010.0,Adventure Animation Comedy Family Fantasy Musi...,Nathan Greno,Brad Garrett,Donna Murphy,M.C. Gainey,7.8,17th century based on fairy tale disney flower...,English
8,Avengers: Age of Ultron,2015.0,Action Adventure Sci-Fi,Joss Whedon,Chris Hemsworth,Robert Downey Jr.,Scarlett Johansson,7.5,artificial intelligence based on comic book ca...,English
9,Harry Potter and the Half-Blood Prince,2009.0,Adventure Family Fantasy Mystery,David Yates,Alan Rickman,Daniel Radcliffe,Rupert Grint,7.5,blood book love potion professor,English
10,Batman v Superman: Dawn of Justice,2016.0,Action Adventure Sci-Fi,Zack Snyder,Henry Cavill,Lauren Cohan,Alan D. Purwin,6.9,based on comic book batman sequel to a reboot ...,English

### I need a better way to categorize the genres and the keywords